### ISSUE TITLE
Readme中一处小错误

### ISSUE THREAD

**Issue by Edge2020** [Repeerc/ExistOS-For-HP39GII#31]
![屏幕截图 2021-01-26 220803](https://user-images.githubusercontent.com/27722335/105855444-0b9ea400-6023-11eb-93d9-7a5d594431c8.png)

此处将“return”打成“ruturn”了

**Comment by Repeerc** [comment]
ok,已修复（

**Comment by Edge2020** [comment]
（其实英文文档还没改

**Comment by Edge2020** [comment]
> ok,已修复（

（其实英文文档还没改

**Comment by Repeerc** [comment]
ok (
