### ISSUE TITLE
源码里的Makefile乱了

### ISSUE THREAD

**Issue by Ukua** [Repeerc/ExistOS-For-HP39GII#37]
1.Makefile和Makefile.linux是反的，后者才是在windows环境下使用的
2.Makefile中对于arm-none-eabi路径用的是path中的路径，而明明tools里就有一套能用的了（旧版release文件里用的就是tools里的）,我安装的arm-none-eabi不兼容，导致make报错

昨天开始折腾这个，反复试了20多遍才发现是Makefile的问题，修改之后编译成功，另外我在尝试用cmake编译的时候同样报错了，不知道arm-none-eabi是不是抽风了，我还在linux环境下尝试过编译，同样报错

而且现阶段功能好少啊，我要如何编写自己的应用程序？

**Comment by Repeerc** [comment]
已经将两个环境的Makefile合并，Win和Linux环境下应该都可以使用。现在还在修改内核，编写应用程序还得等内核完成才可以，在此之前只能将编写的“应用”直接集成至这个不完善的内核中（
